FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["App2.csproj", "./"]
RUN dotnet restore "App2.csproj"
COPY . .
RUN dotnet build "App2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "App2.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "App2.dll"]
